### ISSUE TITLE
[Bug]未检查到发布版本时产生的显示错误

### ISSUE THREAD

**Issue by StonePick** [pokemonchw/BYGUpdateTool#1]
在未检查到发布版本时，“检查更新”按钮下方的“正在检查更新……”字样仍然留存，并且，在后续检查依旧返回无releases时，“正在检查更新……”字样会”堆积“起来，如图。
![image](https://github.com/user-attachments/assets/a2f43ffd-c3e4-4f07-935f-9633e2677111)

**Comment by pokemonchw** [comment]
这玩意还没发布呢阿镐
